name: Scrape and update aggregate evals file on AWS S3

on:
  workflow_dispatch: # Manual run.
  # Suggested run times to pull new data:
  # - Fall quarter: February 15
  # - Winter quarter: May 15
  # - Spring quarter: August 29
  # - Summer quarter: October 24

jobs:
  run:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
      - run: npm ci
        working-directory: backend/web_scraping/evals_data
      - name: Run update script
        run: node index.js
        env:
          SCU_USERNAME: ${{ secrets.SCU_USERNAME }}
          SCU_PASSWORD: ${{ secrets.SCU_PASSWORD }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ vars.AWS_DEFAULT_REGION }}
          SCU_SCHEDULE_HELPER_BUCKET_NAME: ${{ vars.SCU_SCHEDULE_HELPER_BUCKET_NAME }}
          AGGREGATE_EVALS_JSON_GZ_OBJECT_KEY: ${{ vars.AGGREGATE_EVALS_JSON_GZ_OBJECT_KEY }}
          EVALS_AND_TERMS_JSON_GZ_OBJECT_KEY: ${{ vars.EVALS_AND_TERMS_JSON_GZ_OBJECT_KEY }}

        working-directory: backend/web_scraping/evals_data
